### ISSUE TITLE
"Too few arguments to function" when saving Plugin (apparently linked to TinyMCE option)

### ISSUE THREAD

**Issue by woluweb** [nikosdion/DarkMagic#2]
### Steps to reproduce the issue

Installed Dark Magic 2.0.2 on J4.1 running PHP8.0.

### Expected result

On J4 sites where I installed it in the past, it keeps working (even if they are J4.1 and Dark Magic 2.0.2 now)

### Actual result

After enabling plugin and Saving got the following error
An error has occurred.
0 Too few arguments to function Joomla\Plugin\System\DarkMagic\Extension\DarkMagic::forceTinyMceDarkContent(), 1 passed in /home/festivalki/dev/plugins/system/darkmagic/src/Extension/DarkMagic.php on line 234 and exactly 2 expected

### Troubleshooting already performed
I had to rename the folder to be able to uninstall it, reinstall and test again.

Apparently, it is when you enable Backend that the error msg occurs
Now that I read again the error msg I see that it seems to be linked to TinyMCE option (but maybe others, could not test further)

But even if I only enable front-end, it seems to have no effect (even though first tab is set on "always" or "browser").

#### Mandatory information

Issues without this information can not be replied to.

* **Joomla! version**: 4.1
* **Joomla! backend template**: Atum
* **PHP version**: 8.0
* **Server Operating System**: Linux
* **Browser**: Chrome

**Comment by nikosdion** [comment]
If you set the Apply Dark Theme option to Browser it will work correctly. The bug only occurs when you use the Always or Follow The Sun options because of a missing parameter. Thank you for the heads up!
