### ISSUE TITLE
Read more buttons stay light after dark mode applied

### ISSUE THREAD

**Issue by phoenicyan** [nikosdion/DarkMagic#5]
I'm working on moving our website to Joomla 4.2, and one of the requirements - support for Dark Mode. The plugin works great, but Read More buttons are staying light. Is there a setting that makes them dark as well?

Many thanks for the plugin!

**Comment by nikosdion** [comment]
These buttons are styled as `class="btn btn-secondary"`. The secondary button background colour is off-white; it's meant to create contrast against the primary (dark blue) colour per Bootstrap's colour semantics. The colour you see is the right colour indeed.

If you do not like them being secondary buttons you can create a template override and set the button class to `class="btn btn-primary"`.
