### ISSUE TITLE
Cassiopeia gets dark mode while this mode is disabled

### ISSUE THREAD

**Issue by Sulpher** [nikosdion/DarkMagic#6]
I have been installed to test this interesting solution.
Well, the plugin is enabled.
DarkMagic for Joomla!™ 4 > Front-end settings > Frontend Dark Mode - set to NO
<img width="990" alt="Снимок экрана 2023-01-10 в 13 57 52" src="https://user-images.githubusercontent.com/3432048/211534211-16b18a84-4f32-4111-bcb1-38030f3e399e.png">

However, Cassiopeia gets dark mode while it should not.
<img width="954" alt="Снимок экрана 2023-01-10 в 13 58 41" src="https://user-images.githubusercontent.com/3432048/211534397-5b19807e-165b-4656-8337-8f368bbd7f61.png">

DarkMagic for Joomla!™ 4 ver.2.2.0
Joomla 4.2.6
PHP 7.4

**Comment by nikosdion** [comment]
The switch wasn't respected. You can apply the changes from https://github.com/nikosdion/DarkMagic/commit/c8abe466516b50c9f729e2a1f0b7b90628ddb72f to make it work right.
