### ISSUE TITLE
White backgrounds of elements in 4.3

### ISSUE THREAD

**Issue by Jokerminator** [nikosdion/DarkMagic#7]
Thank you a lot for the Dark Magic theme so far!
I have Dark Magic on for admin and front end. Front end looks good. But admin shows these white areas:
<img width="1919" alt="Screenshot 2023-04-20 200935" src="https://user-images.githubusercontent.com/16600503/233452147-c3519a5d-1af2-4c5b-a3d1-736eef2892b5.png">

<img width="1913" alt="Screenshot 2023-04-20 201136" src="https://user-images.githubusercontent.com/16600503/233452154-2d677c4e-49de-43ed-9b9e-1635bba991a3.png">

**Comment by nikosdion** [comment]
Joomla 4.3 uses a newer version of Bootstrap and has some changes in the way it integrates it, hence the wrong colors. I will be addressing these issues over the next two weeks, as I am currently traveling. Expect an update around mid-May.

**Comment by nikosdion** [comment]
I had some time tonight… and it looks that just the cards were affected (and a few minor things I fixed very fast). I also added support for the new Guided Tours feature. I just released version 2.3.0 with all these improvements.
